"""Shipped obligation catalog: the flagship frameworks/regulations GRC engineers track.

`copyright_status` + `display_policy` drive what the UI may ever render for each
obligation (spec 00 invariant 3). Conservative defaults: ISO gets ids_only (litigious),
PCI gets ids_and_titles (SSC publishes summary-of-changes tables publicly)."""

from __future__ import annotations

from sqlalchemy.orm import Session

from oblag.db.models import CopyrightStatus, DisplayPolicy, Obligation

CATALOG: list[dict] = [
    # --- US government works: public domain, full text allowed ---
    dict(
        slug="nist-800-53",
        name="NIST SP 800-53 (Security and Privacy Controls)",
        issuing_body="NIST",
        jurisdiction="US-Federal",
        canonical_url="https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final",
        current_version="Rev. 5",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="nist-csf",
        name="NIST Cybersecurity Framework",
        issuing_body="NIST",
        jurisdiction="US-Federal",
        canonical_url="https://www.nist.gov/cyberframework",
        current_version="2.0",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="nist-800-171",
        name="NIST SP 800-171 (Protecting CUI)",
        issuing_body="NIST",
        jurisdiction="US-Federal",
        canonical_url="https://csrc.nist.gov/pubs/sp/800/171/r3/final",
        current_version="Rev. 3",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="hipaa",
        name="HIPAA Security & Privacy Rules",
        issuing_body="HHS/OCR",
        jurisdiction="US-Federal",
        canonical_url="https://www.hhs.gov/hipaa",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="circia",
        name="CIRCIA Cyber Incident Reporting",
        issuing_body="CISA",
        jurisdiction="US-Federal",
        canonical_url="https://www.cisa.gov/topics/cyber-threats-and-advisories/information-sharing/cyber-incident-reporting-critical-infrastructure-act-2022-circia",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="fedramp",
        name="FedRAMP",
        issuing_body="GSA",
        jurisdiction="US-Federal",
        canonical_url="https://www.fedramp.gov",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="cmmc",
        name="CMMC",
        issuing_body="DoD",
        jurisdiction="US-Federal",
        canonical_url="https://dodcio.defense.gov/cmmc/",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="sox",
        name="Sarbanes-Oxley (ICFR)",
        issuing_body="SEC/PCAOB",
        jurisdiction="US-Federal",
        canonical_url="https://www.sec.gov",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="glba-safeguards",
        name="GLBA Safeguards Rule (16 CFR 314)",
        issuing_body="FTC",
        jurisdiction="US-Federal",
        canonical_url="https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-314",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="coppa",
        name="COPPA Rule (16 CFR 312)",
        issuing_body="FTC",
        jurisdiction="US-Federal",
        canonical_url="https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-312",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="sec-cyber-disclosure",
        name="SEC Cybersecurity Disclosure Rules",
        issuing_body="SEC",
        jurisdiction="US-Federal",
        canonical_url="https://www.sec.gov/rules-regulations",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="nist-800-63",
        name="NIST SP 800-63 (Digital Identity Guidelines)",
        issuing_body="NIST",
        jurisdiction="US-Federal",
        canonical_url="https://csrc.nist.gov/pubs/sp/800/63/4/final",
        current_version="Rev. 4",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="nist-privacy-framework",
        name="NIST Privacy Framework",
        issuing_body="NIST",
        jurisdiction="US-Federal",
        canonical_url="https://www.nist.gov/privacy-framework",
        current_version="1.0",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="fips-140-3",
        name="FIPS 140-3 (Cryptographic Module Validation)",
        issuing_body="NIST",
        jurisdiction="US-Federal",
        canonical_url="https://csrc.nist.gov/pubs/fips/140-3/final",
        current_version="140-3",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    # --- US states ---
    dict(
        slug="nydfs-500",
        name="NYDFS Cybersecurity Regulation (23 NYCRR 500)",
        issuing_body="New York DFS",
        jurisdiction="US-NY",
        canonical_url="https://www.dfs.ny.gov/industry-guidance/cybersecurity-resources",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="ccpa",
        name="CCPA/CPRA + CPPA Regulations",
        issuing_body="California CPPA",
        jurisdiction="US-CA",
        canonical_url="https://cppa.ca.gov/regulations/",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="us-state-privacy",
        name="US State Comprehensive Privacy Laws",
        issuing_body="US state legislatures",
        jurisdiction="US-States",
        canonical_url="https://iapp.org/resources/article/us-state-privacy-legislation-tracker/",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    # --- EU: reusable with attribution ---
    dict(
        slug="gdpr",
        name="GDPR (Regulation 2016/679)",
        issuing_body="EU",
        jurisdiction="EU",
        canonical_url="https://eur-lex.europa.eu/eli/reg/2016/679/oj",
        copyright_status=CopyrightStatus.eu_reuse,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="dora",
        name="DORA (Regulation 2022/2554)",
        issuing_body="EU",
        jurisdiction="EU",
        canonical_url="https://eur-lex.europa.eu/eli/reg/2022/2554/oj",
        copyright_status=CopyrightStatus.eu_reuse,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="nis2",
        name="NIS2 (Directive 2022/2555)",
        issuing_body="EU",
        jurisdiction="EU",
        canonical_url="https://eur-lex.europa.eu/eli/dir/2022/2555/oj",
        copyright_status=CopyrightStatus.eu_reuse,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="eu-ai-act",
        name="EU AI Act (Regulation 2024/1689)",
        issuing_body="EU",
        jurisdiction="EU",
        canonical_url="https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
        copyright_status=CopyrightStatus.eu_reuse,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="eu-cra",
        name="EU Cyber Resilience Act (Regulation 2024/2847)",
        issuing_body="EU",
        jurisdiction="EU",
        canonical_url="https://eur-lex.europa.eu/eli/reg/2024/2847/oj",
        copyright_status=CopyrightStatus.eu_reuse,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="eidas2",
        name="eIDAS 2.0 (Regulation 2024/1183)",
        issuing_body="EU",
        jurisdiction="EU",
        canonical_url="https://eur-lex.europa.eu/eli/reg/2024/1183/oj",
        copyright_status=CopyrightStatus.eu_reuse,
        display_policy=DisplayPolicy.full_text,
    ),
    # --- Other jurisdictions (open/government licences) ---
    dict(
        slug="uk-gdpr",
        name="UK GDPR + Data Protection Act 2018",
        issuing_body="UK ICO / Parliament",
        jurisdiction="UK",
        canonical_url="https://www.legislation.gov.uk/ukpga/2018/12/contents",
        copyright_status=CopyrightStatus.licensed,  # Crown copyright, Open Government Licence
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="pipeda",
        name="PIPEDA (Canada)",
        issuing_body="Parliament of Canada / OPC",
        jurisdiction="CA",
        canonical_url="https://laws-lois.justice.gc.ca/eng/acts/P-8.6/",
        copyright_status=CopyrightStatus.licensed,
        display_policy=DisplayPolicy.full_text,
    ),
    dict(
        slug="lgpd",
        name="LGPD (Brazil, Lei 13.709/2018)",
        issuing_body="Brazil / ANPD",
        jurisdiction="BR",
        canonical_url="https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm",
        copyright_status=CopyrightStatus.public_domain,
        display_policy=DisplayPolicy.full_text,
    ),
    # --- Copyrighted standards: events/IDs only, never body text ---
    dict(
        slug="pci-dss",
        name="PCI DSS",
        issuing_body="PCI SSC",
        jurisdiction="Global",
        canonical_url="https://www.pcisecuritystandards.org/document_library/",
        current_version="4.0.1",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    # --- the rest of the PCI SSC standards family (all copyrighted; RFC/change
    # signals tracked via the pci_ssc adapter, full text via BYOL) ---
    dict(
        slug="pci-pts-poi",
        name="PCI PTS POI (PIN Transaction Security — Point of Interaction)",
        issuing_body="PCI SSC",
        jurisdiction="Global",
        canonical_url="https://www.pcisecuritystandards.org/document_library/",
        current_version="7.0",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="pci-pts-hsm",
        name="PCI PTS HSM (Hardware Security Module Requirements)",
        issuing_body="PCI SSC",
        jurisdiction="Global",
        canonical_url="https://www.pcisecuritystandards.org/document_library/",
        current_version="4.0",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="pci-pin",
        name="PCI PIN Security Requirements",
        issuing_body="PCI SSC",
        jurisdiction="Global",
        canonical_url="https://www.pcisecuritystandards.org/document_library/",
        current_version="3.1",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="pci-p2pe",
        name="PCI P2PE (Point-to-Point Encryption)",
        issuing_body="PCI SSC",
        jurisdiction="Global",
        canonical_url="https://www.pcisecuritystandards.org/document_library/",
        current_version="3.1",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="pci-3ds",
        name="PCI 3DS Core Security Standard",
        issuing_body="PCI SSC",
        jurisdiction="Global",
        canonical_url="https://www.pcisecuritystandards.org/document_library/",
        current_version="1.0",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="pci-secure-software",
        name="PCI Secure Software Standard (Software Security Framework)",
        issuing_body="PCI SSC",
        jurisdiction="Global",
        canonical_url="https://www.pcisecuritystandards.org/document_library/",
        current_version="1.2.1",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="pci-secure-slc",
        name="PCI Secure SLC Standard (Software Security Framework)",
        issuing_body="PCI SSC",
        jurisdiction="Global",
        canonical_url="https://www.pcisecuritystandards.org/document_library/",
        current_version="1.1",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="pci-card-production",
        name="PCI Card Production & Provisioning Security Standards",
        issuing_body="PCI SSC",
        jurisdiction="Global",
        canonical_url="https://www.pcisecuritystandards.org/document_library/",
        current_version="3.0",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="pci-tsp",
        name="PCI TSP (Token Service Provider Security Requirements)",
        issuing_body="PCI SSC",
        jurisdiction="Global",
        canonical_url="https://www.pcisecuritystandards.org/document_library/",
        current_version="1.0",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="pci-mpoc",
        name="PCI MPoC (Mobile Payments on COTS)",
        issuing_body="PCI SSC",
        jurisdiction="Global",
        canonical_url="https://www.pcisecuritystandards.org/document_library/",
        current_version="1.1",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="pci-kmo",
        name="PCI KMO (Key Management Operations)",
        issuing_body="PCI SSC",
        jurisdiction="Global",
        canonical_url="https://www.pcisecuritystandards.org/document_library/",
        # no current_version: v1.0 is still in RFC — nothing is in force yet, so its
        # consultations render on the ordinary first-effectiveness lifecycle
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="iso-27001",
        name="ISO/IEC 27001",
        issuing_body="ISO/IEC",
        jurisdiction="Global",
        canonical_url="https://www.iso.org/standard/27001",
        current_version="2022",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_only,
    ),
    dict(
        slug="iso-27002",
        name="ISO/IEC 27002",
        issuing_body="ISO/IEC",
        jurisdiction="Global",
        canonical_url="https://www.iso.org/standard/75652.html",
        current_version="2022",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_only,
    ),
    dict(
        slug="iso-42001",
        name="ISO/IEC 42001 (AI Management)",
        issuing_body="ISO/IEC",
        jurisdiction="Global",
        canonical_url="https://www.iso.org/standard/42001",
        current_version="2023",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_only,
    ),
    dict(
        slug="soc2",
        name="SOC 2 Trust Services Criteria",
        issuing_body="AICPA",
        jurisdiction="Global",
        canonical_url="https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2",
        current_version="2017 (rev. 2022)",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    # ISO privacy/cloud/BCM extensions — iso.org URLs are auto-watched by the
    # iso_catalog adapter (stage-code tracking). Vanity URLs (follow latest edition)
    # where they exist; numeric pages otherwise (their stage codes flag revisions).
    dict(
        slug="iso-27701",
        name="ISO/IEC 27701 (Privacy Information Management)",
        issuing_body="ISO/IEC",
        jurisdiction="Global",
        canonical_url="https://www.iso.org/standard/27701",
        current_version="2025",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_only,
    ),
    dict(
        slug="iso-27017",
        name="ISO/IEC 27017 (Cloud Security Controls)",
        issuing_body="ISO/IEC",
        jurisdiction="Global",
        canonical_url="https://www.iso.org/standard/43757.html",
        current_version="2015",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_only,
    ),
    dict(
        slug="iso-27018",
        name="ISO/IEC 27018 (PII in Public Clouds)",
        issuing_body="ISO/IEC",
        jurisdiction="Global",
        canonical_url="https://www.iso.org/standard/27018",
        current_version="2019",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_only,
    ),
    dict(
        slug="iso-22301",
        name="ISO 22301 (Business Continuity)",
        issuing_body="ISO",
        jurisdiction="Global",
        canonical_url="https://www.iso.org/standard/75106.html",
        current_version="2019",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_only,
    ),
    dict(
        slug="cis-controls",
        name="CIS Critical Security Controls",
        issuing_body="Center for Internet Security",
        jurisdiction="Global",
        canonical_url="https://www.cisecurity.org/controls",
        current_version="8.1",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="csa-ccm",
        name="CSA Cloud Controls Matrix",
        issuing_body="Cloud Security Alliance",
        jurisdiction="Global",
        canonical_url="https://cloudsecurityalliance.org/research/cloud-controls-matrix",
        current_version="4.0",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.ids_and_titles,
    ),
    dict(
        slug="hitrust-csf",
        name="HITRUST CSF",
        issuing_body="HITRUST Alliance",
        jurisdiction="Global",
        canonical_url="https://hitrustalliance.net/hitrust-framework",
        current_version="11.8",
        copyright_status=CopyrightStatus.copyrighted,
        display_policy=DisplayPolicy.events_only,  # most restrictive licensing
    ),
    dict(
        slug="nerc-cip",
        name="NERC CIP Reliability Standards",
        issuing_body="NERC",
        jurisdiction="US-Federal",
        canonical_url="https://www.nerc.com/pa/Stand/Pages/ReliabilityStandards.aspx",
        copyright_status=CopyrightStatus.licensed,  # standards freely published by NERC
        display_policy=DisplayPolicy.ids_and_titles,
    ),
]


def seed_obligations(session: Session) -> int:
    count = 0
    for entry in CATALOG:
        existing = session.query(Obligation).filter_by(slug=entry["slug"]).one_or_none()
        if existing is None:
            session.add(Obligation(**entry))
        else:
            for key, value in entry.items():
                setattr(existing, key, value)
        count += 1
    session.flush()
    return count
