"""baseline schema

Revision ID: 0afe12c4e89c
Revises:
Create Date: 2026-07-13 23:43:39.237453
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0afe12c4e89c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adapter_health",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("adapter", sa.String(length=64), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("items_seen_last_run", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("adapter"),
    )
    op.create_table(
        "obligation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("issuing_body", sa.String(length=255), nullable=False),
        sa.Column("jurisdiction", sa.String(length=64), nullable=False),
        sa.Column("canonical_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "copyright_status",
            sa.Enum("public_domain", "eu_reuse", "licensed", "copyrighted", name="copyrightstatus"),
            nullable=False,
        ),
        sa.Column(
            "display_policy",
            sa.Enum("full_text", "ids_and_titles", "ids_only", "events_only", name="displaypolicy"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_obligation_slug"), "obligation", ["slug"], unique=True)
    op.create_table(
        "snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=False),
        sa.Column("adapter", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("http_headers", sa.JSON(), nullable=True),
        sa.Column("storage_ref", sa.String(length=255), nullable=False),
        sa.Column("attestation_ref", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_snapshot_sha256"), "snapshot", ["sha256"], unique=True)
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("target", sa.String(length=1024), nullable=True),
        sa.Column("filters", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("jurisdiction", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "proposed",
                "comment_open",
                "comment_closed",
                "final_pending_effective",
                "effective",
                "withdrawn",
                "stalled",
                "superseded",
                name="itemstate",
            ),
            nullable=False,
        ),
        sa.Column("native_status", sa.String(length=255), nullable=True),
        sa.Column("track", sa.String(length=16), nullable=False),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("obligation_id", sa.Integer(), nullable=True),
        sa.Column("resolved_change_id", sa.Integer(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["obligation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_change_id"],
            ["pipeline_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pipeline_item_jurisdiction"), "pipeline_item", ["jurisdiction"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_item_source_system"), "pipeline_item", ["source_system"], unique=False
    )
    op.create_index(op.f("ix_pipeline_item_state"), "pipeline_item", ["state"], unique=False)
    op.create_table(
        "private_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obligation_id", sa.Integer(), nullable=False),
        sa.Column("version_label", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_ref", sa.String(length=255), nullable=False),
        sa.Column("license_attested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["obligation_id"],
            ["obligation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("obligation_id", "version_label", name="uq_private_doc_version"),
    )
    op.create_index(
        op.f("ix_private_document_obligation_id"),
        "private_document",
        ["obligation_id"],
        unique=False,
    )
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pipeline_item_id", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "item_created",
                "state_changed",
                "date_changed",
                "content_changed",
                "item_resolved",
                "anomaly",
                name="eventtype",
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["pipeline_item_id"],
            ["pipeline_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_occurred_at"), "event", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_event_pipeline_item_id"), "event", ["pipeline_item_id"], unique=False)
    op.create_index(op.f("ix_event_type"), "event", ["type"], unique=False)
    op.create_table(
        "join_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pipeline_item_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["pipeline_item_id"],
            ["pipeline_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pipeline_item_id", "type", "value", name="uq_join_key_item_type_value"
        ),
    )
    op.create_index(
        op.f("ix_join_key_pipeline_item_id"), "join_key", ["pipeline_item_id"], unique=False
    )
    op.create_table(
        "key_date",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pipeline_item_id", sa.Integer(), nullable=False),
        sa.Column(
            "date_type",
            sa.Enum(
                "proposal_date",
                "comment_open",
                "comment_close",
                "projected_final",
                "adopted",
                "effective",
                "phased_compliance",
                "entry_into_force",
                "application",
                "transition_deadline",
                name="datetype",
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("value", sa.Date(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "statutory_hard", "published_firm", "agency_estimate", "derived", name="confidence"
            ),
            nullable=False,
        ),
        sa.Column("source_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("asserted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("supersedes_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pipeline_item_id"],
            ["pipeline_item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["key_date.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_key_date_pipeline_item_id"), "key_date", ["pipeline_item_id"], unique=False
    )
    op.create_table(
        "notification_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("watchlist_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlist.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("watchlist_id", "event_id", name="uq_notification_watchlist_event"),
    )
    op.create_index(
        op.f("ix_notification_log_event_id"), "notification_log", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_notification_log_watchlist_id"), "notification_log", ["watchlist_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_log_watchlist_id"), table_name="notification_log")
    op.drop_index(op.f("ix_notification_log_event_id"), table_name="notification_log")
    op.drop_table("notification_log")
    op.drop_index(op.f("ix_key_date_pipeline_item_id"), table_name="key_date")
    op.drop_table("key_date")
    op.drop_index(op.f("ix_join_key_pipeline_item_id"), table_name="join_key")
    op.drop_table("join_key")
    op.drop_index(op.f("ix_event_type"), table_name="event")
    op.drop_index(op.f("ix_event_pipeline_item_id"), table_name="event")
    op.drop_index(op.f("ix_event_occurred_at"), table_name="event")
    op.drop_table("event")
    op.drop_index(op.f("ix_private_document_obligation_id"), table_name="private_document")
    op.drop_table("private_document")
    op.drop_index(op.f("ix_pipeline_item_state"), table_name="pipeline_item")
    op.drop_index(op.f("ix_pipeline_item_source_system"), table_name="pipeline_item")
    op.drop_index(op.f("ix_pipeline_item_jurisdiction"), table_name="pipeline_item")
    op.drop_table("pipeline_item")
    op.drop_table("watchlist")
    op.drop_index(op.f("ix_snapshot_sha256"), table_name="snapshot")
    op.drop_table("snapshot")
    op.drop_index(op.f("ix_obligation_slug"), table_name="obligation")
    op.drop_table("obligation")
    op.drop_table("adapter_health")
    # ### end Alembic commands ###
